services:
  app:
    image: php:8.2-fpm
    volumes:
      - .:/var/www
      
  web:
    image: nginx:alpine
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"   # Change de 8000 à 8080

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata:
